---
- name: >-
    Load setup tasks file for adding the Okta ASA (sftd) package repository
  ansible.builtin.include_tasks:
    file: setup_{{ ansible_os_family }}.yml

- name: Update the cache with the Okta ASA goodness
  ansible.builtin.package:
    update_cache: yes
  # This cache update can cause idempotence to fail, so tell molecule
  # to ignore any changes this task produces when testing idempotence.
  tags:
    - molecule-idempotence-notest

- name: Install Okta ASA (sftd)
  ansible.builtin.package:
    name:
      - scaleft-server-tools

# Unless you do this, systemd can sometimes get confused when you try
# to start a service you just installed.
- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable sftd
  ansible.builtin.service:
    name: sftd
    enabled: yes
